tests/fixtures/mapping-rule-argument-based.yml
tests/mock_galaxy.py
tests/test_mapper_rules.py
vortex/core/helpers.py

Hi @nuwang, I need to write a test for this.  Most lines of code here are straight from galaxy.  I can't think of a better way to do it.
If a jobs arguments are {'input_group1': {'A': 'B', 'C': {'D': 'E'}}}
then {'input_group1': {'A': 'B'}} would match, {'input_group1': {'C': {'D': 'E'}}} would match,
{'input_group1': {'A': 'G'}} would not match, {'input_group1': 'A': 'B', 'C': {'D': 'X'}}} would not match

add functions from galaxys dynamic_tool_destinations.py for making argument-based rules

---

tests/fixtures/mapping-context.yml
tests/test_mapper_context.py
tpv/core/entities.py

Two failing tests for context variables used within rules:
(1) large_input_size is set to 60 for tool bwa.  The rule will fail the job if input_size > large_input_size.  The job fails with input size 40 because it is using the parent value (20) for large_input_size.
(2) tool canu has context variable 'smallish_input_size' which does not exist on any of the ancestor entities.  At the of evaluation (early?) this variable does not exist so the job fails.
I'm not sure whether (2) should work or whether context variables must always be defined globally and then overridden.  (1) needs to work for context variables to be used in rules.

Add context tests for context variables accessed within rules

---

tests/fixtures/mapping-destinations.yml
tests/test_mapper_destinations.py
tpv/core/entities.py
tpv/core/mapper.py

Hi @nuwang, I've been testing to see how to get the cores for the job during a destination rule.  I'm pretty sure this matches but it fails the job (no destinations available) rather than raising the exception.

Add a failing test for a destination rule raising a JobNotReadyException

---

tests/fixtures/job_conf.yml
tests/fixtures/mapping-destinations.yml
tests/test_mapper_destinations.py
tpv/core/mapper.py

@cat-bro Is this what's expected with destination name overrides? The destination must still exist in job_conf though, the only difference is that a custom name can be given. We could modify it so even a job_conf entry is not required, but that seems unnecessary?
@bgruening This PR adds support for custom naming if required by Galaxy EU: https://github.com/usegalaxy-eu/sorting-hat/blob/0b0758a1b8b72bc0ea5ae198ad2949f4aa16b586/sorting_hat.py#L186

Add support for overriding destination name

---

tpv/core/util.py

Otherwise I was getting:
```pytb
Traceback (most recent call last):
File "/home/nate/.virtualenvs/tpvdev2/bin/tpv", line 33, in <module>
sys.exit(load_entry_point('total-perspective-vortex', 'console_scripts', 'tpv')())
File "/home/nate/.virtualenvs/tpvdev2/bin/tpv", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File …
```

Use ruamel.yaml in tpv.core.util since PyYAML is not a dependency

---

tests/test_entity.py
tpv/core/entities.py
tpv/core/mapper.py

Originally, the loader was not an attribute of an entity. It was added later as a performance optimization, so that all entities could share the same code cache for compiled fragments. Ironically, it has had the opposite effect, resulting in exponential memory use and increase in runtime. This is because the existing code for deep cloning was now inadvertently deep-cloning the loader too, which in turn references *all* available entities. This PR makes sure the loader attribute is shallow-copied when deep-copying entities.
Fixes: https://github.com/galaxyproject/total-perspective-vortex/issues/53

Avoid deepcopying loader when cloning entities

---

tests/fixtures/formatter/formatter-basic.yml
tests/test_shell.py
tpv/core/formatter.py

This PR makes the following improvements to the formatter.
1. Fields within rules are also formatted in the same order
2. Context vars are not sorted. They appear in their original order.
3. Params and envs are sorted alphabetically.
4. users now appear after roles, but before destinations.

Improve formatting of entities and add more tests

---

docs/topics/concepts.rst
docs/topics/configure_galaxy.rst
docs/topics/tpv_by_example.rst

Noted that most yaml examples have an additional space in the beginning which annoyed me a bit when copy pasting. Hope that this is fixing it

fix indentation

---

docs/topics/tpv_by_example.rst
tpv/core/entities.py
tpv/core/mapper.py

In Galaxy job destinations/environments, `env` is a list, where each element is a dict with one of three formats:
```yaml
env:
- name: FOO
value: foo
- file: /bar
- execute: /baz
```
In TPV, env is instead a dict where keys are vars and values are their values. These are converted into a list of `{"name": k, "value": v}` dicts when the job destination is constructed. Because static destinations in the Galaxy job conf are no longer required as of TPV 2.0.0, it's desirable to be able to define destinations and complex envs fully in the TPV config.
This change supports the list syntax but is backwards compatible with the dict syntax. It overwrites any values on merging where names/keys match, and preserves the ordering of any existing env entries when merging. Any non-matching env entries …

Convert env to a list compatible with Galaxy job conf

---

tpv/core/helpers.py

closes: https://github.com/galaxyproject/total-perspective-vortex/issues/83

Add initializer to handle empty sequence when reducing

---

tests/fixtures/mapping-role.yml
tests/test_mapper_role.py
tpv/core/helpers.py

Add a helper that takes an entity and two lists of tags, one to match and one to exclude. Returns true if the entity has every tag from the include list and no tags from the exclude list.
This is useful for a Galaxy Australia training rule that uses tool tags in deciding resource allocations for training jobs.

Add helper for checking entity tags within a tpv rule

---

tests/fixtures/mapping-role.yml
tests/test_mapper_role.py
tpv/core/entities.py

Broken test PR
Role rules no longer have access to the tool tags and tool ID. These are some prints from running the test of the role rule helper with a tool that has tool rules. In TPV v1 we were able to access the scheduling tags for the tool being used in these rules.
```
evaluating default_training_rule:
entity: <class 'tpv.core.entities.Rule'> id=fastqc_small_input_rule, abstract=False, cores=2, mem=7.6, gpus=None, min_cores = None, min_mem = None, min_gpus = None, max_cores = None, max_mem = None, max_gpus = None, env=None, params=None, resubmit=None, tags=<class 'tpv.core.entities.TagSetManager'> tags=[], rank=, inherits=None, context=None, if=input_size, execute=, fail=
entity.tpv_tags: <class 'tpv.core.entities.TagSetManager'> tags=[]
postive tag condition: True
negative tag …
```

If a tool has file size rules, a role rule has no access to tool's scheduling tags

---

tests/fixtures/mapping-rule-tool-limits.yml
tests/test_mapper_rules.py
tpv/commands/test/mock_galaxy.py
tpv/core/helpers.py

Add a helpers to make it easier to reason about tool versions. Currently this is cumbersome, see https://github.com/usegalaxy-au/infrastructure/blob/master/files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml#L652-L655

Add helpers for tool version comparison

---

docs/topics/tpv_by_example.rst
tests/fixtures/mapping-destinations.yml
tests/test_mapper_destinations.py
tpv/core/entities.py

If the user has rules, the entity is deemed to have too large a requirement for cores/RAM to run, even though toolshed_hifiasm will run with 2 cores for a job with <1TB input size.

Failing test for pulsar user scenario

---

tpv/core/mapper.py

Otherwise there's no way to know where the error actually is in your configs other than manual searching.

When regex compilation fails, log what was attempting to be compiled

---

tests/fixtures/mapping-destinations.yml
tests/test_mapper_destinations.py
tpv/core/entities.py

The current code does not cover the case when they are defined to be zero.
Let's see whether this small change passes the tests. If it does then it gives usegalaxy.eu a chance to fix GPU scheduling using rules in a kind of ugly but not horrible way.

Match cores, mem and gpus whenever they are defined

---

tests/fixtures/mapping-resubmit.yml
tests/fixtures/resubmit/exit_code_oom_no_resubmit.xml
tests/fixtures/resubmit/exit_code_oom_with_resubmit.xml

on the 2nd submission the env variables get lost: see https://github.com/galaxyproject/galaxy/pull/9747 .. https://github.com/galaxyproject/galaxy/pull/12852
For some reason bash evaluates this as successful even if the if statement crashes. so actually there are only 2 submissions (1 resubmission), i.e. multiple resubmissions still do not work.
Even if the tests are not executed at the moment I would suggest to fix them by doing a "real OOM" resubmission and treat the case of a lost variable as error.

fix resubmission tests

---

tpv/commands/test/mock_galaxy.py
tpv/core/helpers.py

Fixes:
```
Oct 13 14:29:40 galaxy-vgp galaxyctl[2536822]:   File "/cvmfs/main.galaxyproject.org/venv/lib/python3.8/site-packages/tpv/core/helpers.py", line 16, in get_dataset_size
Oct 13 14:29:40 galaxy-vgp galaxyctl[2536822]:     return float(dataset.file_size)
Oct 13 14:29:40 galaxy-vgp galaxyctl[2536822]: TypeError: float() argument must be a string or a number, not 'NoneType'
```
There's an underlying bug as well where the job state is final but the file size is unset, but I would always consider it better to use one abstraction level above the database column.

Fix get_dataset_size for datasets with null file_size column

---

tests/test_entity.py
tpv/core/entities.py
tpv/core/loader.py

These functions allow a dict representation of Destination objects which is convenient for example for serializebility

Add to to_dict functions to Destination and TagSetManager classes

---

tests/test_helpers.py
tpv/commands/test/mock_galaxy.py
tpv/core/helpers.py

This will be used in the ESG WP4 TPV meta-scheduling API for decision-making. If you think this is not useful for a larger audience, please close this PR.

Add a helper to get the object store ids and the datasets size for every dataset in a job

---

.github/workflows/tests.yaml
requirements_test.txt
tests/conftest.py
tests/test_mapper_resubmit.py

depends on: https://github.com/galaxyproject/galaxy/pull/15205

Add optional slow tests

---

tests/fixtures/formatter/formatter-tool-sort-order-formatted.yml
tests/fixtures/formatter/formatter-tool-sort-order-input.yml
tests/fixtures/linter/linter-invalid-regex.yml
tests/fixtures/linter/linter-warnings.yml
tests/test_shell.py
tpv/commands/formatter.py
tpv/commands/linter.py
tpv/commands/shell.py
tpv/core/loader.py
tpv/core/util.py

Related discussion in https://github.com/galaxyproject/tpv-shared-database/issues/73.
~~I looked a bit at adding `#noqa` support but reading comments and figuring out the line they are associated with seemed a bit tricky. But if it's something we want I could work on that. Alternatively, `tpv lint --ignore=...` to simply ignore an entire class of warnings would be easy to implement, but then it's all-or-nothing.~~
I went ahead and added `# noqa` and command line `tpv lint --ignore=...` support. `# noqa` comments apply to the whole entity they are contained within and can either be without a specific code (in which case all warnings are ignored) or can specify codes as a comma-separated list like `# noqa: T101, T102, ...`. Inline `# noqa` comments are not supported.
IMO you'd probably not …

Add lint warning for tools with `cores` and no `mem`

---

tests/fixtures/mapping-rules.yml
tests/test_shell.py
tpv/commands/dryrunner.py
tpv/commands/shell.py
tpv/commands/test/mock_galaxy.py

To properly test our configuration I have added options for roles and history-tags to dryrun.

Enhancement for dryrun: add --roles and --history-tags arguments

---

requirements_test.txt
tests/fixtures/job_conf.xml
tests/test_mapper_sample.py
tpv/rules/gateway.py

I'm still using xml based job config (and will need to stick to it for a while, since I use macros a lot) and could not thing of a way to configure multiple TPV config files .. maybe like so?

Add posibility to load multiple configs from xml job config

---

setup.cfg
tests/fixtures/linter/linter-invalid-regex.yml
tests/fixtures/mapping-destinations.yml
tests/fixtures/mapping-invalid-regex.yml
tests/fixtures/mapping-invalid-tags.yml
tests/fixtures/mapping-rank.yml
tests/fixtures/mapping-role.yml
tests/fixtures/mapping-rule-argument-based.yml
tests/fixtures/mapping-rules-changed.yml
tests/fixtures/mapping-rules.yml
tests/fixtures/mapping-user-invalid-tags.yml
tests/fixtures/mapping-user.yml
tests/fixtures/scenario-too-many-highmem-jobs.yml
tests/test_entity.py
tests/test_mapper_basic.py
tests/test_mapper_user.py
tox.ini
tpv/__init__.py
tpv/commands/linter.py
tpv/core/entities.py
tpv/core/evaluator.py
tpv/core/helpers.py
tpv/core/loader.py
tpv/core/mapper.py

Add a well-defined schema for the TPV config with stronger typing support.

Add pydantic support

---

tpv/core/helpers.py

For issue https://github.com/galaxyproject/total-perspective-vortex/issues/115
calling parse_version(X) where X is None will cause an exception to be thrown. This can be prevented by catching the Nones beforehand.
I haven’t tested this locally.

Wrap tool version comparision in a function that checks for None
